version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
        user: root

    environment:
      TZ: /usr/share/zoneinfo/America/Los_Angeles
      TRAVIS_REPO_SLUG: facebook/react

      # In production you should use endpoint https://api.knapsackpro.com
      # which is default so it means you don't need to set KNAPSACK_PRO_ENDPOINT
      # Below endpoint is just for internal tests by KnapsackPro developers.
      KNAPSACK_PRO_ENDPOINT: https://api-staging.knapsackpro.com

    parallelism: 4

    steps:
      # dependencies
      # clone @knapsack-pro/core project
      - run:
          name: Checkout code of @knapsack-pro/core
          command: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-core-js.git)

      - restore_cache:
          keys:
            - v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-knapsack-pro-core-

      - run: cd ~/knapsack-pro-core-js && yarn install
      - run: cd ~/knapsack-pro-core-js && yarn run build
      - run: cd ~/knapsack-pro-core-js && yarn link

      - save_cache:
          name: Saving Cache of @knapsack-pro/core
          key: v1-knapsack-pro-core-{{ checksum "~/knapsack-pro-core-js/package.json" }}
          paths:
            - ~/knapsack-pro-core-js/node_modules

      # clone @knapsack-pro/jest project
      - run:
          name: Checkout code of @knapsack-pro/jest
          command: cd ~ && (git clone -b $CIRCLE_BRANCH --single-branch https://github.com/KnapsackPro/knapsack-pro-jest.git || git clone --single-branch https://github.com/KnapsackPro/knapsack-pro-jest.git)

      - restore_cache:
          keys:
            - v1-knapsack-pro-jest-{{ checksum "~/knapsack-pro-jest/package.json" }}
            # fallback to the latest cache if no exact match is found
            - v1-knapsack-pro-jest-

      - run: cd ~/knapsack-pro-jest && yarn install
      - run: cd ~/knapsack-pro-jest && yarn link @knapsack-pro/core
      - run: cd ~/knapsack-pro-jest && yarn run build
      - run: cd ~/knapsack-pro-jest && yarn link

      - save_cache:
          name: Saving Cache of @knapsack-pro/jest
          key: v1-knapsack-pro-jest-{{ checksum "~/knapsack-pro-jest/package.json" }}
          paths:
            - ~/knapsack-pro-jest/node_modules

      # clone react project
      - checkout

      - run: echo $CIRCLE_COMPARE_URL | cut -d/ -f7

      - restore_cache:
          name: Restore node_modules cache
          keys:
            - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-node-{{ arch }}-{{ .Branch }}-
            - v1-node-{{ arch }}-

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      # use local version of @knapsack-pro/cypress to test it
      - run: yarn link @knapsack-pro/jest

      # - run:
      #     name: Test Packages
      #     command: ./scripts/circleci/test_entry_point.sh

      - run:
          name: Test Packages
          command: $(yarn bin)/knapsack-pro-jest

      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - store_artifacts:
          path: ./node_modules.tgz

      - store_artifacts:
          path: ./scripts/error-codes/codes.json
